# Generated by Django 3.0.5 on 2020-11-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0003_patentner'),
    ]

    operations = [
        migrations.AddField(
            model_name='patentner',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patentner',
            name='patent_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patentner',
            name='custom_entities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patentner',
            name='default_entities',
            field=models.TextField(blank=True),
        ),
    ]
